export const web3ProviderActions = {
  DETECT_WALLET: "DETECT_WALLET",
  CONNECT_WALLET: "CONNECT_WALLET",
  DISCONNECT_WALLET: "DISCONNECT_WALLET",
  ACCOUNT_STATE_CHANGED: "ACCOUNT_STATE_CHANGED",
};
